# Generated by Django 2.0.4 on 2018-04-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alphabed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Elifba', max_length=255)),
                ('letters', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
